name: trading_helper
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tradeicon.png"
  min_sdk_android: 21 


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf  

  
